import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add all three trial tokens */}
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_DETECT_LANGUAGE}
        />
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_SUMMARIZE}
        />
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_TRANSLATE}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
